export enum Fruits {
    Manzana = "manzana",
    Banana = "banana",
    Naranja = "naranja",
    Uva = "uva",
    Pera = "pera",
    Kiwi = "kiwi",
    Mango = "mango",
    Sandía = "sandía",
    Piña = "piña",
    Melón = "melón",
    Limón = "limón",
    Fresa = "fresa",
    Cereza = "cereza",
    Arándano = "arándano",
    Mandarina = "mandarina",
    Pomelo = "pomelo",
    Mora = "mora",
    Papaya = "papaya",
    Melocotón = "melocotón",
    Albaricoque = "albaricoque",
    Ciruela = "ciruela",
    Mamey = "mamey",
    Guayaba = "guayaba",
    Higo = "higo",
    Granada = "granada",
    Frambuesa = "frambuesa",
    Morera = "morera",
    Grosella = "grosella",
    Membrillo = "membrillo",
    Maracuyá = "maracuyá",
    Guanábana = "guanábana",
    Caqui = "caqui",
    Carambola = "carambola",
    Chirimoya = "chirimoya",
    Guayote = "guayote",
    Zapote = "zapote",
    Lichí = "lichí",
    Tamarindo = "tamarindo",
    Níspero = "níspero",
    Mangostán = "mangostán",
    Nuez = "nuez",
    Pistacho = "pistacho",
    Avellana = "avellana",
    Almendra = "almendra",
    Castaña = "castaña",
    Cacahuete = "cacahuete",
    Coco = "coco",
    Aceituna = "aceituna"
}

export enum Vegetables {
    Zanahoria = "zanahoria",
    Brócoli = "brócoli",
    Espinaca = "espinaca",
    Calabaza = "calabaza",
    Tomate = "tomate",
    Cebolla = "cebolla",
    Pepino = "pepino",
    Lechuga = "lechuga",
    Pimiento = "pimiento",
    Apio = "apio",
    Remolacha = "remolacha",
    Berenjena = "berenjena",
}

export enum Cheese {
    Cheddar = "cheddar",
    Mozzarella = "mozzarella",
    Gouda = "gouda",
    Parmesano = "parmesano",
    Brie = "brie",
    Camembert = "camembert",
    Roquefort = "roquefort",
    Gorgonzola = "gorgonzola",
    Feta = "feta",
    Provolone = "provolone",
    Manchego = "manchego",
    QuesoAzul = "queso azul",
}

