name: Test Eccommerce App

on:
  # push:
  #   branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # environment:
    #   name: DEV
    strategy:
      matrix:
        node-version: [17.x]
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      PORT: ${{ secrets.PORT }}
      DB_URL_MONGO: ${{ secrets.DB_URL_MONGO }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}


    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Debug Secrets
        run: |
          echo "NODE_ENV: $NODE_ENV"
          echo "PORT: $PORT"
          echo "DB_URL_MONGO: $DB_URL_MONGO"
          echo "JWT_SECRET: $JWT_SECRET"
          echo "COOKIE_SECRET: $COOKIE_SECRET"
      
      - name: Run tests
        run: npm run test
      # - name: Build Docker image
      #   run: docker build -t test-app .

      # - name: Run tests in container
      #   run: docker run --rm test-app
